spring:
  application:
    name: trip-ai-agent
  ai:
    dashscope:
      api-key: "sk-04a4f8f9e8f44812af9ac789e610081c"
      chat:
        options:
          model: qwen-plus
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jd.tripaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
